-- Banco separado para Deploy Previews.
-- Execute este arquivo no SQL Editor do projeto Supabase Preview.
-- Não contém dados reais dos jogadores.

create table if not exists public.gardens (
  id bigint generated by default as identity primary key,
  username text not null unique,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create index if not exists gardens_updated_at_idx on public.gardens (updated_at desc);

create table if not exists public.payment_orders (
  id bigint generated by default as identity primary key,
  order_id text not null unique,
  username text not null,
  kit text not null,
  amount numeric(10,2) not null,
  status text not null default 'pending',
  mercado_pago_payment_id text,
  paid_at timestamptz,
  webhook_payload jsonb,
  created_at timestamptz not null default now()
);

create index if not exists payment_orders_username_idx on public.payment_orders (username);
create index if not exists payment_orders_status_idx on public.payment_orders (status);
create unique index if not exists payment_orders_mp_id_idx
  on public.payment_orders (mercado_pago_payment_id)
  where mercado_pago_payment_id is not null;

alter table public.gardens enable row level security;
alter table public.payment_orders enable row level security;

-- O app acessa o banco exclusivamente pelas Netlify Functions.
-- O preview usa a service_role key nas operações de escrita protegidas.
drop policy if exists "preview gardens read" on public.gardens;
create policy "preview gardens read" on public.gardens
  for select to anon, authenticated using (true);

drop policy if exists "preview gardens write" on public.gardens;
create policy "preview gardens write" on public.gardens
  for insert to anon, authenticated with check (true);

drop policy if exists "preview gardens update" on public.gardens;
create policy "preview gardens update" on public.gardens
  for update to anon, authenticated using (true) with check (true);

-- Pedidos devem ser consultados apenas pelas Functions com service_role.
-- Nenhuma policy pública é criada para payment_orders.
